# coding: utf-8

"""
    sdk.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agones_python_sdk.models.sdk_game_server_status import SdkGameServerStatus

class TestSdkGameServerStatus(unittest.TestCase):
    """SdkGameServerStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SdkGameServerStatus:
        """Test SdkGameServerStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SdkGameServerStatus`
        """
        model = SdkGameServerStatus()
        if include_optional:
            return SdkGameServerStatus(
                state = '',
                address = '',
                addresses = [
                    agones_python_sdk.models.status_address.StatusAddress(
                        type = '', 
                        address = '', )
                    ],
                ports = [
                    agones_python_sdk.models.status_port.StatusPort(
                        name = '', 
                        port = 56, )
                    ],
                players = agones_python_sdk.models.[stage:alpha]
[feature_flag:player_tracking].[Stage:Alpha]
[FeatureFlag:PlayerTracking](
                    count = '', 
                    capacity = '', 
                    ids = [
                        ''
                        ], ),
                counters = {
                    'key' : agones_python_sdk.models.[stage:beta]
[feature_flag:counts_and_lists].[Stage:Beta]
[FeatureFlag:CountsAndLists](
                        count = '', 
                        capacity = '', )
                    },
                lists = {
                    'key' : agones_python_sdk.models.[stage:beta]
[feature_flag:counts_and_lists].[Stage:Beta]
[FeatureFlag:CountsAndLists](
                        capacity = '', 
                        values = [
                            ''
                            ], )
                    }
            )
        else:
            return SdkGameServerStatus(
        )
        """

    def testSdkGameServerStatus(self):
        """Test SdkGameServerStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
