# coding: utf-8

"""
    sdk.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agones_python_sdk.api.sdk_api import SDKApi


class TestSDKApi(unittest.TestCase):
    """SDKApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SDKApi()

    def tearDown(self) -> None:
        pass

    def test_allocate(self) -> None:
        """Test case for allocate

        Call to self Allocation the GameServer
        """
        pass

    def test_get_game_server(self) -> None:
        """Test case for get_game_server

        Retrieve the current GameServer data
        """
        pass

    def test_health(self) -> None:
        """Test case for health

        Send a Empty every d Duration to declare that this GameSever is healthy
        """
        pass

    def test_ready(self) -> None:
        """Test case for ready

        Call when the GameServer is ready
        """
        pass

    def test_reserve(self) -> None:
        """Test case for reserve

        Marks the GameServer as the Reserved state for Duration
        """
        pass

    def test_set_annotation(self) -> None:
        """Test case for set_annotation

        Apply a Annotation to the backing GameServer metadata
        """
        pass

    def test_set_label(self) -> None:
        """Test case for set_label

        Apply a Label to the backing GameServer metadata
        """
        pass

    def test_shutdown(self) -> None:
        """Test case for shutdown

        Call when the GameServer is shutting down
        """
        pass

    def test_watch_game_server(self) -> None:
        """Test case for watch_game_server

        Send GameServer details whenever the GameServer is updated
        """
        pass


if __name__ == '__main__':
    unittest.main()
