# coding: utf-8

"""
    sdk.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agones_python_sdk.models.status_counter_status import StatusCounterStatus

class TestStatusCounterStatus(unittest.TestCase):
    """StatusCounterStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatusCounterStatus:
        """Test StatusCounterStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatusCounterStatus`
        """
        model = StatusCounterStatus()
        if include_optional:
            return StatusCounterStatus(
                count = '',
                capacity = ''
            )
        else:
            return StatusCounterStatus(
        )
        """

    def testStatusCounterStatus(self):
        """Test StatusCounterStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
