# coding: utf-8

"""
    sdk.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agones_python_sdk.models.sdk_key_value import SdkKeyValue

class TestSdkKeyValue(unittest.TestCase):
    """SdkKeyValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SdkKeyValue:
        """Test SdkKeyValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SdkKeyValue`
        """
        model = SdkKeyValue()
        if include_optional:
            return SdkKeyValue(
                key = '',
                value = ''
            )
        else:
            return SdkKeyValue(
        )
        """

    def testSdkKeyValue(self):
        """Test SdkKeyValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
