# coding: utf-8

# flake8: noqa

"""
    sdk.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from agones_python_sdk.api.sdk_api import SDKApi

# import ApiClient
from agones_python_sdk.api_response import ApiResponse
from agones_python_sdk.api_client import ApiClient
from agones_python_sdk.configuration import Configuration
from agones_python_sdk.exceptions import OpenApiException
from agones_python_sdk.exceptions import ApiTypeError
from agones_python_sdk.exceptions import ApiValueError
from agones_python_sdk.exceptions import ApiKeyError
from agones_python_sdk.exceptions import ApiAttributeError
from agones_python_sdk.exceptions import ApiException

# import models into sdk package
from agones_python_sdk.models.game_server_object_meta import GameServerObjectMeta
from agones_python_sdk.models.game_server_spec import GameServerSpec
from agones_python_sdk.models.game_server_spec_health import GameServerSpecHealth
from agones_python_sdk.models.googlerpc_status import GooglerpcStatus
from agones_python_sdk.models.protobuf_any import ProtobufAny
from agones_python_sdk.models.sdk_duration import SdkDuration
from agones_python_sdk.models.sdk_game_server import SdkGameServer
from agones_python_sdk.models.sdk_game_server_status import SdkGameServerStatus
from agones_python_sdk.models.sdk_key_value import SdkKeyValue
from agones_python_sdk.models.status_address import StatusAddress
from agones_python_sdk.models.status_counter_status import StatusCounterStatus
from agones_python_sdk.models.status_list_status import StatusListStatus
from agones_python_sdk.models.status_player_status import StatusPlayerStatus
from agones_python_sdk.models.status_port import StatusPort
from agones_python_sdk.models.stream_result_of_sdk_game_server import StreamResultOfSdkGameServer
